export default {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',

    REMOVE_TOKEN: 'REMOVE_TOKEN',

    ADD_USERNAME: 'ADD_USERNAME',

    ITEMS_REQUEST: 'ITEMS_REQUEST',
    ITEMS_SUCCESS: 'ITEMS_SUCCESS',
    ITEMS_FAILURE: 'ITEMS_FAILURE',

    ADD_ITEMS_SUCCESS:'ADD_ITEMS_SUCCESS',

    ADD_STATES_REQUEST: 'ADD_STATES_REQUEST',
    ADD_STATES_SUCCESS:'ADD_STATES_SUCCESS',
    ADD_STATES_FAILURE: 'ADD_STATES_FAILURE',
    REDUCE_ITEMS_STATES: 'REDUCE_ITEMS_STATES'
};